baseURL: https://tzhangmam23.netlify.app/
languageCode: en-us
title: Portfolio website for Tianyi Zhang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Know more about me and my past projects
#      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi! I'm Tianyi
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Gloucester Place, NW1 6BL
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: tzhang.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (440) 7421897465/ (86) 13501642653
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    enable: yes
    social:
    #  - icon: fa-twitter
    #    label: Twitter
    #    url: https://www.twitter.com
    #  - icon: fa-facebook
    #    label: Facebook
    #    url: https://www.facebook.com
    #  - icon: fa-instagram
    #    label: Instagram
    #    url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Timsssssssss
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/tianyi-zhang-7a8b531b3/
  image: ''
  name: Tianyi Zhang
  navigation:
    button1:
      - name: Get Started
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: PERSONAL WEBSITE
    title: TIANYI ZHANG
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
#        subtitle: Ipsum Dolor Sit Amet
        title: Several Facts About Me
        url: blogs/ab
      - image: pic02.jpg
#        subtitle: Feugiat Amet Tempus
        title: My Career Narrative
        url: blogs/wk
      - image: store.jpg
#       subtitle: Lorem Etiam Nullam
        title: ML Model to Predict Future Offtake
        url: blogs/danone
      - image: lend.jpg
#       subtitle: Lorem Etiam Nullam
        title: Regression Models to Predict Interest Rate
        url: blogs/lend 
      - image: weibo.jpg
#       subtitle: Lorem Etiam Nullam
        title: Sentiment Analysis
        url: blogs/weibo
      - image: brexit.jpg
#       subtitle: Lorem Etiam Nullam
        title: Dplyr and Visualization in R
        url: blogs/proj2
#      - image: data.jpg
#       subtitle: Lorem Etiam Nullam
#        title: SF-Rentals Analysis
#        url: blogs/proj1
      
#  two:
#    buttonText: More Projects? Just Click Here
#    enable: yes
#    #subtitle: "N/A"
#    title: YOU HIT THE BOTTOM
#    url: blogs
