baseURL: https://tzhangmam23.netlify.app/
languageCode: en-us
title: Portfolio website for Tianyi Zhang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
#    subtitle: |-
#      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
#      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Tianyi Zhang:CUHKSZ 2018; LBS MAM 2023
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Gloucester Place, NW1 6BL
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: tzhang.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 7421897465
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    #copyright: Company Name
    #enable: yes
    #quicklinks:
    #  - alt: HTML5 UP
    #    text: 'Design: '
    #    url: https://www.html5up.net
    social:
    #  - icon: fa-twitter
    #    label: Twitter
    #    url: https://www.twitter.com
    #  - icon: fa-facebook
    #    label: Facebook
    #    url: https://www.facebook.com
    #  - icon: fa-instagram
    #    label: Instagram
    #    url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/Timsssssssss
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/tianyi-zhang-7a8b531b3
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
#        subtitle: Ipsum Dolor Sit Amet
        title: Academic Background
        url: blogs/ab
      - image: pic02.jpg
#        subtitle: Feugiat Amet Tempus
        title: Work Experience
        url: blogs/wk
      - image: pic03.jpg
#        subtitle: Lorem Etiam Nullam
        title: More about my self
        url: blogs/myself
