---
categories:  
- ""    #the front matter should be like the one found in, e.g., blog2.md. It cannot be like the normal Rmd we used
- ""
date: "2022-09-14"
description: My LBS Statistics Ptoject2 using R # the title that will show up once someone gets to this page
draft: false
image: brexit.jpg # save picture in \static\img\blogs. Acceptable formats= jpg, jpeg, or png . Your iPhone pics wont work

keywords: ""
slug: proj2 # slug is the shorthand URL address... no spaces plz
title: AM_01_HW3
---



<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical. The meaning of each variable can be found by bringing up the help file:</p>
<pre class="r"><code>?yrbss
data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1…
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema…
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, …
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;…
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa…
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1…
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2, …
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not …
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not…
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, …
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,…
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, …
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;…</code></pre>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<pre class="r"><code># Retrieve overall summary statistics
skimr::skim(yrbss)</code></pre>
<table>
<caption>(#tab:distribution and summary statistics)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table style="width:100%;">
<colgroup>
<col width="30%" />
<col width="12%" />
<col width="16%" />
<col width="4%" />
<col width="4%" />
<col width="7%" />
<col width="10%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="22%" />
<col width="10%" />
<col width="15%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="5%" />
<col width="6%" />
<col width="6%" />
<col width="7%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Add BMI column
yrbss_bmi &lt;- yrbss %&gt;% 
  mutate(BMI = weight/(height^2)) 

# Calculate weight summary statistics
yrbss_bmi %&gt;% 
  group_by(gender) %&gt;% 
  drop_na(gender) %&gt;% 
  summarise(mean_weight = mean(weight, na.rm = TRUE),
            median_weight = median(weight, na.rm = TRUE),
            stdv_weight = sd(weight, na.rm = TRUE),
            min_weight = min(weight, na.rm = TRUE),
            max_weight = max(weight, na.rm = TRUE),
            mean_bmi = mean(BMI, na.rm = TRUE),
            median_bmi = median(BMI, na.rm= TRUE),
            min_bmi = min(BMI, na.rm = TRUE),
            max_bmi = max(BMI, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 2 × 10
##   gender mean_…¹ media…² stdv_…³ min_w…⁴ max_w…⁵ mean_…⁶ media…⁷ min_bmi max_bmi
##   &lt;chr&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1 female    61.9    59.0    14.4    29.9    148.    23.5    22.3    13.2    54.3
## 2 male      73.6    70.3    17.1    31.8    181.    23.8    22.7    13.1    53.5
## # … with abbreviated variable names ¹​mean_weight, ²​median_weight, ³​stdv_weight,
## #   ⁴​min_weight, ⁵​max_weight, ⁶​mean_bmi, ⁷​median_bmi</code></pre>
<pre class="r"><code># Create density plot to visualize distribution
yrbss %&gt;% 
  ggplot(aes(x=weight))+
  geom_density()+
  labs(title = &quot;The distribution of high schoolers weight follows a right-skewed distribution&quot;,
       subtitle = &quot;Density plot of high schoolers weight in kg&quot;,
       x = &quot;Weight&quot;,
       y = &quot;Density&quot;) +
  theme_bw() +
  # Add vertical lines to show median and mean
  geom_vline(xintercept = 67.91, size = 0.5, color = &quot;red&quot;) +
  geom_text(aes(x = 75, label = paste0(&quot;Mean\n&quot;,67.91), y = 0.008)) + # Add label to the mean line
  geom_vline(xintercept = 64.41, size = 0.5, color = &quot;blue&quot;) +
  geom_text(aes(x = 56, label = paste0(&quot;Median\n&quot;,64.41), y = 0.008)) #  Add label to the median line</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/distribution%20and%20summary%20statistics-1.png" width="960" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Create boxplot to show quartiles and outliers
yrbss_bmi %&gt;% 
  drop_na(gender) %&gt;% 
  ggplot(aes(x = BMI)) +
  geom_boxplot() +
  labs(title = &quot;More than 25% of high schoolers are overweight based on their BMI&quot;,
       subtitle = &quot;Boxplot of high schoolers BMI&quot;,
       x = &quot;BMI&quot;) +
  facet_wrap(~ gender) +
  theme_bw() +
  theme(axis.ticks.y=element_blank(),
        axis.text.y=element_blank())</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/distribution%20and%20summary%20statistics-2.png" width="960" style="display: block; margin: auto;" /></p>
<p>By first looking at the summary statistics of of the weight variable, we observe an overall average weight of 67.91 kilograms. Considering the physical differences between men and women in terms of height and build, we are not surprised to see a significant difference in the average weight by gender. It should also be mentioned that the summary statistics encompass the entirety of high school, a phase during which teenagers usually are still growing. We can therefore expect a difference in the average weights between grades, which do not necessarily signal deficient or excess weight. The density plot of the overall student sample displays a right-skewed distribution. It therefore makes sense to use the median as the expected value, which is 59 and 70.3 kg respectively for female and male students. While weight gives some indication of the health of high schoolers, other factors such as height should also be considered. We have therefore added a body mass index (BMI) column. In general, a BMI of 25+ is considered overweight. By looking at the boxplots created, we can see that p75 is above 25 for both female and male students. This means that more than 25% of students in the sample are considered overweight, including some signficant outliers. Especially the maximum BMI value of 54.3 should leave us worried for teenagers´health.</p>
<blockquote>
<p>How many observations are we missing weights from?</p>
</blockquote>
<p>By looking at the second column of the <code>skimr::skim function</code>, we can see that there are 1004 entries missing for the weight variable.</p>
<pre class="r"><code>skimr::skim(yrbss)</code></pre>
<table>
<caption>(#tab:skim_yrbss)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table style="width:100%;">
<colgroup>
<col width="30%" />
<col width="12%" />
<col width="16%" />
<col width="4%" />
<col width="4%" />
<col width="7%" />
<col width="10%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="22%" />
<col width="10%" />
<col width="15%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="5%" />
<col width="6%" />
<col width="6%" />
<col width="7%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(yrbss)</code></pre>
<pre><code>##       age          gender             grade             hispanic        
##  Min.   :12.0   Length:13583       Length:13583       Length:13583      
##  1st Qu.:15.0   Class :character   Class :character   Class :character  
##  Median :16.0   Mode  :character   Mode  :character   Mode  :character  
##  Mean   :16.2                                                           
##  3rd Qu.:17.0                                                           
##  Max.   :18.0                                                           
##  NA&#39;s   :77                                                             
##      race               height         weight      helmet_12m       
##  Length:13583       Min.   :1      Min.   : 30    Length:13583      
##  Class :character   1st Qu.:2      1st Qu.: 56    Class :character  
##  Mode  :character   Median :2      Median : 64    Mode  :character  
##                     Mean   :2      Mean   : 68                      
##                     3rd Qu.:2      3rd Qu.: 76                      
##                     Max.   :2      Max.   :181                      
##                     NA&#39;s   :1004   NA&#39;s   :1004                     
##  text_while_driving_30d physically_active_7d hours_tv_per_school_day
##  Length:13583           Min.   :0.0          Length:13583           
##  Class :character       1st Qu.:2.0          Class :character       
##  Mode  :character       Median :4.0          Mode  :character       
##                         Mean   :3.9                                 
##                         3rd Qu.:7.0                                 
##                         Max.   :7.0                                 
##                         NA&#39;s   :273                                 
##  strength_training_7d school_night_hours_sleep
##  Min.   :0            Length:13583            
##  1st Qu.:0            Class :character        
##  Median :3            Mode  :character        
##  Mean   :3                                    
##  3rd Qu.:5                                    
##  Max.   :7                                    
##  NA&#39;s   :1176</code></pre>
<p>Next, consider the possible relationship between a high schooler’s weight and their physical activity.</p>
<p>Plotting the data is a useful first step because it helps us quickly visualize trends, identify strong associations, and develop research questions. Let’s create a new variable in the dataframe <code>yrbss</code>, called <code>physical_3plus</code> , which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise. You may also want to calculate the number and % of those who are and are not active for more than 3 days.</p>
<blockquote>
<p>Use the <code>count()</code> function and see if you get the same results as <code>group_by()... summarise()</code></p>
</blockquote>
<pre class="r"><code>#Create physical_3plus
yrbss_new &lt;- yrbss %&gt;% 
  mutate(physical_3plus=if_else(physically_active_7d &gt; 2,&quot;yes&quot;,&quot;no&quot;)) %&gt;% 
  drop_na(physical_3plus) 

#Using group_by() and summarise()
yrbss_proportion_summarise&lt;-yrbss_new %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(n=n()) %&gt;%
  mutate(pro = n/sum(n)) 
yrbss_proportion_summarise</code></pre>
<pre><code>## # A tibble: 2 × 3
##   physical_3plus     n   pro
##   &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt;
## 1 no              4404 0.331
## 2 yes             8906 0.669</code></pre>
<pre class="r"><code>#Using count()
yrbss_proportion_count&lt;-yrbss_new %&gt;% 
  count(physical_3plus== &quot;yes&quot;) %&gt;% 
  mutate(pro = n/sum(n))
yrbss_proportion_count</code></pre>
<pre><code>## # A tibble: 2 × 3
##   `physical_3plus == &quot;yes&quot;`     n   pro
##   &lt;lgl&gt;                     &lt;int&gt; &lt;dbl&gt;
## 1 FALSE                      4404 0.331
## 2 TRUE                       8906 0.669</code></pre>
<p>Can you provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</p>
<pre class="r"><code># Retrieve number of physical_3plus = no as value
no_proportion&lt;-as.numeric(yrbss_proportion_summarise %&gt;% 
  filter(physical_3plus == &quot;no&quot;) %&gt;% 
  select(n) )

# Retrieve number of physical_3plus = yes as value
yes_proportion&lt;-as.numeric(yrbss_proportion_summarise %&gt;% 
  filter(physical_3plus == &quot;yes&quot;) %&gt;% 
  select(n))

# Create confidence interval
prop.test(no_proportion,no_proportion+yes_proportion)</code></pre>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  no_proportion out of +no_proportion out of no_proportionno_proportion out of yes_proportion
## X-squared = 1522, df = 1, p-value &lt;2e-16
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.323 0.339
## sample estimates:
##     p 
## 0.331</code></pre>
<p>Make a boxplot of <code>physical_3plus</code> vs. <code>weight</code>.</p>
<pre class="r"><code># Create boxplot of weight dependent on physical activity
yrbss_new %&gt;% 
  ggplot(aes(x=physical_3plus,y=weight))+
  geom_boxplot()+
  theme_bw() +
  labs(title = &quot;Highschoolers engaging in more frequent exercise display higher weight levels&quot;,
       subtitle = &quot;Boxplots of weight for high schoolers for different amounts of exercise&quot;,
       x = &quot;At least 3 days of exercise per week?&quot;,
       y = &quot;Weight&quot;) </code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/boxplot-1.png" width="960" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Is there a relationship between these two variables? What did you expect and why?</p>
</blockquote>
<p>When looking at the boxplots, we can observe a lot of overlap, usually associated with a weak relationship. Nevertheless, while the median for the more active students is only slightly higher visually, even a 2 kg difference in the mean is a considerable amount at that age and can affect health. We would naturally expect more active students to be fitter and weigh less. However,there are some other factors we should consider when evaluating the relationship. As we have no data about individual nutrition and the difference in metabolism between students, we cannot claim that the sport has no effect. It can be argued that students with a high metabolism or healthier nutrition have a generally lower weight and do not need to engage in sports regularly to keep a low weight. High schoolers that eat less healthy and have poorer metabolism engage in sport to achieve the same weight as their skinnier peers. Secondly, with exercise comes muscle growth, with are widely known to have a higher weight than fat. Therefore, weight is perhaps not the best measurement of the sports effect. To assess the effect of the sport, a future study should measure body fat percentage and observe the high schoolers’ over a period and measuring change from the starting weight.</p>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean, SD, etc. weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code># Calculate mean weight for less and more exercising students
yrbss_new %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarize(mean_weight_physical_3plus=mean(weight,na.rm=TRUE))</code></pre>
<pre><code>## # A tibble: 2 × 2
##   physical_3plus mean_weight_physical_3plus
##   &lt;chr&gt;                               &lt;dbl&gt;
## 1 no                                   66.7
## 2 yes                                  68.4</code></pre>
<pre class="r"><code># Create dataframes for confidence intervals, split by exercise
yes_physical_3plus&lt;-yrbss_new %&gt;% 
  drop_na() %&gt;% 
  filter(physical_3plus==&quot;yes&quot;)

no_physical_3plus&lt;-yrbss_new %&gt;% 
  drop_na() %&gt;% 
  filter(physical_3plus==&quot;no&quot;)

# Confidence Interval for weight in &quot;Yes&quot; group 
yes_confidence_interval &lt;- lm(weight~1,yes_physical_3plus)
confint(yes_confidence_interval,level=0.95)</code></pre>
<pre><code>##             2.5 % 97.5 %
## (Intercept)  68.3   69.1</code></pre>
<pre class="r"><code># Confidence Interval for weight in &quot;No&quot; group 
no_confidence_interval &lt;- lm(weight~1,no_physical_3plus)
confint(no_confidence_interval,level=0.95)</code></pre>
<pre><code>##             2.5 % 97.5 %
## (Intercept)  66.5   67.8</code></pre>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<blockquote>
<p>Write the null and alternative hypotheses for testing whether mean weights are different for those who exercise at least three times a week and those who don’t.</p>
</blockquote>
<p><strong>H0</strong> = Being active for 60 minutes at least 3 days a week has no effect on high schoolers’ weight
<strong>H1</strong> = Being active for 60 minutes at least 3 days a week affects high schoolers’ weight</p>
<pre class="r"><code># Create confidence interval for the difference in mean in weight between high schoolers exercising less and more than 3 days a week
t.test(weight ~ physical_3plus, data = yrbss_new)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group no mean in group yes 
##              66.7              68.4</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we will introduce a new function, <code>hypothesize</code>, that falls into the infer workflow. You will use this method for conducting hypothesis tests.</p>
<p>But first, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code># Initialize hypothesis test
obs_diff &lt;- yrbss_new %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Notice how you can use the functions specify and calculate again like you did for calculating confidence intervals. Here, though, the statistic you are searching for is the difference in means, with the order being yes - no != 0.</p>
<p>After you have initialized the test, you need to simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code># Set seed for reproducibility
set.seed(1234)

null_dist &lt;- yrbss_new %&gt;%
  # specify variables
  specify(weight ~ physical_3plus) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Here, <code>hypothesize</code> is used to set the null hypothesis as a test for independence, i.e., that there is no difference between the two population means.</p>
<blockquote>
<p>In one sample cases, the null argument can be set to <em>point</em> to test a hypothesis relative to a point estimate.</p>
</blockquote>
<p>Also, note that the <code>type</code> argument within generate is set to permute, which is the argument when generating a null distribution for a hypothesis test.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code># Plot null distribution
ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()+
  theme_bw()</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/visualize_null-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.77. We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code># Visualize obs_stat
null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/infer_get_p-1.png" width="960" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Calculate p-value
null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>This the standard workflow for performing hypothesis tests.</p>
</div>
</div>
<div id="imdb-ratings-differences-between-directors" class="section level1">
<h1>IMDB ratings: Differences between directors</h1>
<p>Recall the IMBD ratings data. I would like you to explore whether the mean IMDB rating for Steven Spielberg and Tim Burton are the same or not. I have already calculated the confidence intervals for the mean ratings of these two directors and as you can see they overlap.</p>
<p>First, I would like you to reproduce this graph. You may find <code>geom_errorbar()</code> and <code>geom_rect()</code> useful.</p>
<p>In addition, you will run a hypothesis test. You should use both the <code>t.test</code> command and the <code>infer</code> package to simulate from a null distribution, where you assume zero difference between the two.</p>
<blockquote>
<p>Before anything, write down the null and alternative hypotheses, as well as the resulting test statistic and the associated t-stat or p-value. At the end of the day, what do you conclude?</p>
</blockquote>
<p><strong>H0</strong> = There is no difference in the average IMDB rating of Tim Burton and Steven Spielberg movies
<strong>H1</strong> = There is a difference in the average IMDB rating of Tim Burton and Steven Spielberg movies</p>
<p>You can load the data and examine its structure</p>
<pre class="r"><code># Load and glimpse movie data
movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Avenge…
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;…
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevorrow…
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015, 20…
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93, 1…
## $ gross               &lt;dbl&gt; 7.61e+08, 6.59e+08, 6.52e+08, 6.23e+08, 5.33e+08, …
## $ budget              &lt;dbl&gt; 2.37e+08, 2.00e+08, 1.50e+08, 2.20e+08, 1.85e+08, …
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, 920…
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658, 9…
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752, 35…
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7.2, …</code></pre>
<pre class="r"><code># Create list to filter for directors of interest
direc &lt;- c(&quot;Tim Burton&quot;,&quot;Steven Spielberg&quot;)
library(ggrepel)

movies %&gt;% 
  # filter and group for directors
  filter(director %in% direc) %&gt;% 
  group_by(director) %&gt;% 
  # Calculate summary statistics
  summarize(mean_rating = mean(rating),
            sd_rating = sd(rating),
            count = n(),
            t_critical = qt(0.975, count-1)) %&gt;%
  mutate(x_min = mean_rating - t_critical*sd_rating/sqrt(count), 
         x_max = mean_rating + t_critical*sd_rating/sqrt(count) ) %&gt;% 
  # Create confidence interval plot for directors
  ggplot(aes(x = mean_rating,y=director, colour = director,
         label = round(mean_rating,2), size = 10))+
  geom_pointrange(aes(xmin=x_min,xmax=x_max),size=1)+
  geom_errorbar(aes(xmin = x_min, xmax = x_max),
                width = 0.1, size = 1.2) +
  # Creating grey angle to mark overlap between intervals
  geom_rect(aes(xmin = x_min[1], xmax = x_max[2], 
            ymin = 0, ymax = 3),
            alpha = 1/8,color = NA) +
  # Add labels of margins of the confidence intervals
  geom_text(aes(label = round(x_min,2), x=x_min),
            vjust = -1, size = 3.5,
            color = &quot;black&quot;) +
  geom_text(aes(label = round(x_max,2), x=x_max), 
            vjust = -1, size = 3.5,
            color = &quot;black&quot;) +
  geom_text(aes(label = round(mean_rating,2), x=mean_rating),
            vjust = -1, size = 5,
            color = &quot;black&quot;) +
  # Format plot
  scale_y_discrete(limits = c(&quot;Tim Burton&quot;,&quot;Steven Spielberg&quot;))+
  theme_bw()+
  theme(legend.position = &quot;none&quot;)+
  labs(title = &quot;Do Spielberg and Burton have the same mean IMDB ratings?&quot;,
       subtitle = &quot;95% confidence intervals overlap&quot;,
       x = &quot;Mean IMDB Rating&quot;, 
       y = NULL) +
  theme(plot.title = element_text(face=&quot;bold&quot;))</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/director_plot-1.png" width="960" style="display: block; margin: auto;" /></p>
<pre class="r"><code>direc_data &lt;- movies %&gt;% 
  filter(director %in% direc) %&gt;% 
  group_by(director) %&gt;% 
  summarize(rating, n = n())

# Run t-test   
t.test(rating ~ director, data = direc_data )</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  rating by director
## t = 3, df = 31, p-value = 0.01
## alternative hypothesis: true difference in means between group Steven Spielberg and group Tim Burton is not equal to 0
## 95 percent confidence interval:
##  0.16 1.13
## sample estimates:
## mean in group Steven Spielberg       mean in group Tim Burton 
##                           7.57                           6.93</code></pre>
<p>As we can see from the two sample t-test, we reject the null hypothesis as 0 does not lie within the confidence interval. We can therefore say with 95% confidence that there is a signifcant difference in the average rating of Steven Spielberg and Tim Burton films. The graph confirms this, as we see only a very small and seemingly insignificant overlap between the confidence intervals. Specifically, we also see that the difference stems from Steven Spielberg having a <strong>higher</strong> average rating. Nevertheless, it should be mentioned that the sample size for both directors is rather low, with a correspondingly high t_critical. As more movies come out and the ratings do not drastically deviate from the current average, we might expect to not see any more overlap of the confidence intervals in the future.</p>
<p>Personally, we enjoy Beetlejuice just as much as Jurassic Park.</p>
</div>
<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>You are asked to carry out the analysis. The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<pre class="r"><code># Load and glimpse the data
omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635…
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma…
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3…</code></pre>
</div>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender ?</h2>
<p>The data frame <code>omega</code> contains the salaries for the sample of 50 executives in the company. Can you conclude that there is a significant difference between the salaries of the male and female executives? Note that you can perform different types of analyses, and check whether they all lead to the same conclusion</p>
<p>. Confidence intervals . Hypothesis testing . Correlation analysis . Regression</p>
<p>Calculate summary statistics on salary by gender. Also, create and print a dataframe where, for each gender, you show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% confidence interval</p>
<pre class="r"><code># Summary Statistics with favstats
mosaic::favstats(salary ~ gender, data=omega)</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Summary statistics including confidence interval with formula
omega_summary &lt;- omega %&gt;% 
  group_by(gender) %&gt;% 
  summarize(mean_salary = mean(salary),
            sd_salary = sd(salary),
            sample_size = n(),
            t_critical = qt(0.975,sample_size-1),
            se_salary = sd_salary/sqrt(sample_size),
            margin_of_error = t_critical * se_salary,
            salary_low = mean_salary - margin_of_error,
            salary_high = mean_salary + margin_of_error)
omega_summary</code></pre>
<pre><code>## # A tibble: 2 × 9
##   gender mean_salary sd_salary sample_…¹ t_cri…² se_sa…³ margi…⁴ salar…⁵ salar…⁶
##   &lt;chr&gt;        &lt;dbl&gt;     &lt;dbl&gt;     &lt;int&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1 female      64543.     7567.        26    2.06   1484.   3056.  61486.  67599.
## 2 male        73239.     7463.        24    2.07   1523.   3151.  70088.  76390.
## # … with abbreviated variable names ¹​sample_size, ²​t_critical, ³​se_salary,
## #   ⁴​margin_of_error, ⁵​salary_low, ⁶​salary_high</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough.</p>
</blockquote>
<p>A glimpse at the summary statistics table provides some clarity of the salary distribution. It is clearly visible that the standard deviation, sample size, standard error and margin of error are very similar for both genders. Meanwhile, the min and max values of the confidence intervals don’t overlap. This essentially tells us that while male and female employees both experience the same variance of salaries within their gender (most likely due to position), the average from which these salaries vary from is significantly different. We can therefore claim with 95% confidence that the true average salary for the female population at Omega is lower than that of the male population.</p>
<p>You can also run a hypothesis testing, assuming as a null hypothesis that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money. You should tun your hypothesis testing using <code>t.test()</code> and with the simulation method from the <code>infer</code> package.</p>
<pre class="r"><code># Set seed for reproducibility
set.seed(1234)

# Initialize hypothesis testing
obs_diff_salary &lt;- omega %&gt;%
  specify(salary ~ gender) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;male&quot;, &quot;female&quot;))

# hypothesis testing using t.test() 
t.test(salary~gender,data=omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<pre class="r"><code># hypothesis testing using infer package
hypothesis_testing_salary&lt;-omega %&gt;% 
  # specify variables
  specify(salary~gender) %&gt;% 
  # assume independence, i.e, there is no difference
  hypothesize(null=&quot;independence&quot;) %&gt;% 
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000,type=&quot;permute&quot;) %&gt;% 
  # calculate statistic of difference, namely &quot;diff in means
  calculate(stat=&quot;diff in means&quot;)

# Visualize hypothesis testing
hypothesis_testing_salary %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff_salary, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/hypothesis_testing-1.png" width="960" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Get p-value
hypothesis_testing_salary %&gt;%
  get_p_value(obs_stat = obs_diff_salary, direction = &quot;two-sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough.</p>
</blockquote>
<p>We reject the null hypothesis that there is no difference in average salary at Omega based on gender. A p-value of 0.0002 is statistically significant and the confidence interval of the two sample t-test does not include 0. The graph also highlights that a bootstrap simulation yields the same result. The red line informs us that the observed difference is outside the values we would expect if there was no significant difference in salaries. It should also be mentioned that the t-test for the difference in means shows the confidence interval of how much less female employees earn on average compared to men.</p>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience. A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of salary by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<blockquote>
<p>Based on this evidence, can you conclude that there is a significant difference between the experience of the male and female executives?</p>
</blockquote>
<p>Looking at the quartile values, we can see that Q3 for female employees is lower than Q1 of male employees. If we were to graph the experience grouped by gender, we would see that the IQR of female and male experience would not overlap. This means that we can safely say that at least 75% of male employees in the sample have more experience than female employees. While this might indicate a statistically significant difference in means, we cannot confidently claim that the average experience of female employees at Omega is lower than that of men. We should conduct a hypothesis test.</p>
<blockquote>
<p>Perform similar analyses as in the previous section. Does your conclusion validate or endanger your conclusion about the difference in male and female salaries?</p>
</blockquote>
<pre class="r"><code># Set seed for reproducibility
set.seed(1234)

# Initialize hypothesis testing
obs_diff_exp &lt;- omega %&gt;%
  specify(experience ~ gender) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;male&quot;, &quot;female&quot;))

# hypothesis testing using t.test() 
t.test(experience~gender,data=omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means between group female and group male is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<pre class="r"><code># hypothesis testing using infer package
hypothesis_testing_exp&lt;-omega %&gt;% 
  # specify variables
  specify(experience~gender) %&gt;% 
  # assume independence, i.e, there is no difference
  hypothesize(null=&quot;independence&quot;) %&gt;% 
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000,type=&quot;permute&quot;) %&gt;% 
  # calculate statistic of difference, namely diff in means
  calculate(stat=&quot;diff in means&quot;)

# Visualize hypothesis testing
hypothesis_testing_exp %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff_exp, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/hypothesis_testing2-1.png" width="960" style="display: block; margin: auto;" /></p>
<pre class="r"><code># Get p-value
hypothesis_testing_exp %&gt;%
  get_p_value(obs_stat = obs_diff_exp, direction = &quot;two-sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>The hypothesis test supports our prior expectation that there is a significant difference in the means of education between female and male employees. The confidence interval of the two sample t-test for the difference in means does not include 0 and the p-value is considerable lower than 0.05. We reject the null hypothesis, and claim 95% confidence that the average experience of women at Omega is lower than that of men. Again, it should be mentioned that we are working with a rather small sample size. And while the experience is lower, we would expect that this is not the only factor affecting salary. Discrimination might still be at work.</p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<blockquote>
<p>Analyse the relationship between salary and experience.</p>
</blockquote>
<p>Draw a scatterplot to visually inspect the data.</p>
<pre class="r"><code># Create a scatterplot for salary and experience
omega %&gt;% 
  ggplot(aes(x = experience,y = salary, color = gender)) + 
  geom_point() + 
  geom_smooth(method = &quot;lm&quot;, se = FALSE)+
  theme_bw() +
  labs(title = &quot;The scatterplot does not support the claim of discrimination&quot;,
       subtitle = &quot;Scatterplot of experience and salary by gender&quot;,
       x = &quot;Experience in Years&quot;,
       y = &quot;Annual Salary in USD&quot;)</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/salary_exp_scatter-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>You can use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make this plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/ggpairs-1.png" width="960" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Look at the salary vs experience scatterplot. What can you infer from this plot? Explain in a couple of sentences</p>
</blockquote>
<p>When looking at the scatterplot, we can see that female employees in the sample have less experience than their male counterparts, as discussed earlier. We can also observe that employees with no experience are exclusively female. We cannot safely claim from the scatterplot that there is systematic discrimination at work at Omega. First of all, the low amount of data points make a best-fit line rather imprecise. Secondly, while there are male employees earning more than their female counterparts for certain years of experience, there are also men with more experience earning the same or less. A regression controlling for factors such as position and department would paint a clearer picture of whether women earn less in the exact same position than men. Nevertheless, we see that men in the sample earn higher salaries, with most observations at the top of the y axis belonging to males. It can be argued that while women might not get significantly less money for a given job, Omega prefers to hire men for their more senior and better paid jobs. This would of course also be discrimination, however slightly less easy to detect.</p>
</div>
</div>
<div id="challenge-1-brexit-plot" class="section level1">
<h1>Challenge 1: Brexit plot</h1>
<p>Using your data manipulation and visualisation skills, please use the Brexit results dataframe (the same dataset you used in the pre-programme assignment) and produce the following plot. Use the correct colour for each party; google “UK Political Party Web Colours” and find the appropriate hex code for colour, not the default colours that R gives you.</p>
<pre class="r"><code>brexit &lt;- read_csv(&quot;https://raw.githubusercontent.com/kostis-christodoulou/am01/master/data/brexit_results.csv&quot;)</code></pre>
<pre class="r"><code>brexit %&gt;% 
  # Pivot the data into longer format so that parties are in the same column
  pivot_longer(col = 2:5,
               names_to = &quot;party&quot;,
               values_to = &quot;percent&quot;) %&gt;% 
  ggplot(aes(x = percent, y = leave_share,color = party))+
  # Set the transparency of the points to be 0.5
  geom_point(size = 2.5,alpha = 0.3)+
  # Draw a fitted line with standard error
  geom_smooth(method = &quot;lm&quot;, se = TRUE)+
  # Assign color for each party
  scale_color_manual(labels = c(&quot;Conservative&quot;, &quot;Labour&quot;,&quot;Lib Dems&quot;,&quot;UKIP&quot;),
                     values = c(&quot;#0087DC&quot;, &quot;#E32636&quot;,&quot;#FDBB30&quot;,&quot;#6D3177&quot;)) +
  theme_bw()+
  theme(legend.position = &quot;bottom&quot;,legend.title = element_blank())+
  scale_y_continuous(breaks=seq(20, 100, 20),
                     limits = c(20,100))+
  scale_x_continuous(breaks=seq(0, 80, 20),
                     limits = c(0,80))+
  labs(title=&quot;How political affiliation translated to Brexit Voting&quot;,
       x=&quot;Party % in the UK 2015 general election&quot;,
       y = &quot;Leave % in the 2016 Brexit referendum&quot;)</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/brexit-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
<div id="challenge-2gdp-components-over-time-and-among-countries" class="section level1">
<h1>Challenge 2:GDP components over time and among countries</h1>
<p>The GDP data we will look at is from the <a href="https://unstats.un.org/unsd/snaama/Downloads">United Nations’ National Accounts Main Aggregates Database</a>, which contains estimates of total GDP and its components for all countries from 1970 to today. We will look at how GDP and its components have changed over time, and compare different countries and how much each component contributes to that country’s GDP. The file we will work with is <a href="http://unstats.un.org/unsd/amaapi/api/file/6">GDP and its breakdown at constant 2010 prices in US Dollars</a> and it has already been saved in the Data directory. Have a look at the Excel file to see how it is structured and organised</p>
<pre class="r"><code>UN_GDP_data  &lt;-  read_excel(here::here(&quot;data&quot;, &quot;Download-GDPconstant-USD-countries.xls&quot;), # Excel filename
                sheet=&quot;Download-GDPconstant-USD-countr&quot;, # Sheet name
                skip=2) # Number of rows to skip</code></pre>
<p>The first thing you need to do is to tidy the data, as it is in wide format and you must make it into long, tidy format. Please express all figures in billions (divide values by <code>1e9</code>, or <span class="math inline">\(10^9\)</span>), and you want to rename the indicators into something shorter.</p>
<pre class="r"><code>tidy_GDP_data  &lt;-  UN_GDP_data %&gt;%
  pivot_longer(cols = 4:51,
               names_to = &quot;year&quot;,
               values_to = &quot;value&quot;) %&gt;% 
  # Turning the selected columns&#39; data type into dbl
  mutate(year = as.double(year),value = as.double(value),
         value = value/1e9)

glimpse(tidy_GDP_data)</code></pre>
<pre><code>## Rows: 176,880
## Columns: 5
## $ CountryID     &lt;dbl&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,…
## $ Country       &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanista…
## $ IndicatorName &lt;chr&gt; &quot;Final consumption expenditure&quot;, &quot;Final consumption expe…
## $ year          &lt;dbl&gt; 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 19…
## $ value         &lt;dbl&gt; 5.56, 5.33, 5.20, 5.75, 6.15, 6.32, 6.37, 6.90, 7.09, 6.…</code></pre>
<pre class="r"><code># Let us compare GDP components for these 3 countries
country_list &lt;- c(&quot;United States&quot;,&quot;India&quot;, &quot;Germany&quot;)</code></pre>
<pre class="r"><code>tidy_GDP_data %&gt;% 
  filter(Country %in% country_list,
         IndicatorName %in% c(&quot;Gross capital formation&quot;,
                              &quot;Exports of goods and services&quot;,
                              &quot;General government final consumption expenditure&quot;,
                              &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;,
                              &quot;Imports of goods and services&quot;)) %&gt;% 
  ggplot(aes(x = year, y = value,color = IndicatorName))+
  geom_line(size = 1)+
  facet_wrap(~Country)+
  scale_color_discrete(labels = c(&quot;Gross capital formation&quot;, 
                                  &quot;Exports&quot;,&quot;Government expenditure&quot;,
                                  &quot;Household expenditure&quot;,&quot;Imports&quot;))+
  labs(title=&quot;GDP components over time&quot;,
       subtitle = &quot;In constant 2010 USD&quot;,
       x= NULL,
       y = &quot;Billion US$&quot;,
       color = &quot;Components of GDP&quot;)+
  theme_bw()</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/plot1-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>Secondly, recall that GDP is the sum of Household Expenditure (Consumption <em>C</em>), Gross Capital Formation (business investment <em>I</em>), Government Expenditure (G) and Net Exports (exports - imports). Even though there is an indicator <code>Gross Domestic Product (GDP)</code> in your dataframe, I would like you to calculate it given its components discussed above.</p>
<blockquote>
<p>What is the % difference between what you calculated as GDP and the GDP figure included in the dataframe?</p>
</blockquote>
<pre class="r"><code>tidy_GDP_recalc &lt;- tidy_GDP_data %&gt;% 
 filter(Country %in% country_list,
        IndicatorName %in% c(&quot;Gross capital formation&quot;,
                             &quot;Exports of goods and services&quot;,
                             &quot;General government final consumption expenditure&quot;,
                             &quot;Household consumption expenditure (including Non-profit institutions serving households)&quot;,
                             &quot;Imports of goods and services&quot;,
                             &quot;Gross Domestic Product (GDP)&quot;)) %&gt;% 
 mutate(value = value / 10^9) %&gt;% 
 # pivot the data set wider so that the types show in different columns
 pivot_wider(names_from = IndicatorName,values_from = value) %&gt;% 
 # calculate the net export, total GDP and difference between given and calculated GDP
 mutate(Net_Exports = `Exports of goods and services` - `Imports of goods and services`,
        GDP_recalc = `Gross capital formation` + `General government final consumption expenditure`+
         `Household consumption expenditure (including Non-profit institutions serving households)`+
          Net_Exports,
        GDP_diff = formattable::percent(`GDP_recalc`-`Gross Domestic Product (GDP)`)/`GDP_recalc`)

# Show percentage change
tidy_GDP_recalc %&gt;% 
  select(Country, year, GDP_diff)</code></pre>
<pre><code>## # A tibble: 144 × 3
##    Country  year GDP_diff  
##    &lt;chr&gt;   &lt;dbl&gt; &lt;formttbl&gt;
##  1 Germany  1970 2.94%     
##  2 Germany  1971 3.42%     
##  3 Germany  1972 3.43%     
##  4 Germany  1973 2.84%     
##  5 Germany  1974 1.75%     
##  6 Germany  1975 2.84%     
##  7 Germany  1976 2.76%     
##  8 Germany  1977 2.69%     
##  9 Germany  1978 2.96%     
## 10 Germany  1979 3.33%     
## # … with 134 more rows
## # ℹ Use `print(n = ...)` to see more rows</code></pre>
<pre class="r"><code>tidy_GDP_recalc %&gt;% 
 # pivot the indicator names longer, leaving GDP as a column
 pivot_longer(col = c(4,5,6,10),names_to = &quot;IndicatorName&quot;,values_to = &quot;value&quot;) %&gt;% 
 # Calculate the proportion
 mutate(proportion = value / GDP_recalc) %&gt;% 
 ggplot(aes(x = year, y = proportion,color = IndicatorName))+
 geom_line(size = 1)+
 facet_wrap(~Country)+
 scale_color_discrete(labels = c(&quot;Government Expenditure&quot;,
                                 &quot;Gross capital formation&quot;,
                                 &quot;Household Expenditure&quot;,
                                 &quot;Net Exports&quot;))+
 labs(title=&quot;GDP and its breakdown at constant 2010 prices in US Dollars&quot;,
      x= NULL,
      y = &quot;proportion&quot;,
      caption = &quot;\nSource: United Nations, http://unstats.un.org/unsd/snaama/Downloads&quot;,color = NULL)+
 scale_y_continuous(labels = scales::percent)+
 theme_bw()</code></pre>
<p><img src="/blogs/group8-homework3_files/figure-html/plot2-1.png" width="960" style="display: block; margin: auto;" /></p>
<blockquote>
<p>What is this last chart telling you? Can you explain in a couple of paragraphs the different dynamic among these three countries?</p>
</blockquote>
<p>To commence our analysis, we would like to look at the similarities between the countries. It is clearly visible that household expenditure is by far the highest contributor to GDP in all countries. This is perfectly expected in general economics. For the remaining the parts of the GDP, the order of magnitude of their contribution is also approximately the same for all countries. India and USA share a trade deficit for most of the years. This might be tracked back to China, the largest importer for both USA and India. Especially for Germany and the USA, we can see that the components of the GDP comprise approximately the same percentage respectively. This is to be expected, as these countries are considered developed countries of similar economy and society, generally speaking. India however is a completely different story.</p>
<p>The first thing that becomes apparent is that India has visibly lower government expenditure than the comparison countries. This is not unusual for low-income countries, as they spend less on things such as <a href="https://ourworldindata.org/government-spending#recent-data-on-the-size-of-governments">social protection</a>, health care and unemployment benefits. Nevertheless, India´s government expenditure is still within a reasonable margin and has increased in recent years. Another interesting finding is the continual percentage contribution decrease in household expenditure since 1970. An explanation is quickly found, as we can observe gross capital formation mirroring the change in reverse. We can deduct that the Indian population is investing more of their disposable income into assets, rather than spending it. It would prove interesting to identify the precise reason for this shift.</p>
<p>The USA also displayed a shift of components, however here it concerns government expenditure and capital formation. The shift might be attributed largely to the government adapting their spending policy, investing more heavily in infrastructure and military machinery than intangible benefits for the public. As we can also see, the USA is the only country for which the proportion of household expenditure follows has a positive slope. With the simultaneously increasing trade deficit, we can assume that US citizens increased their spending of foreign goods. This could be related to improving trade routes with China and Europe, as well as the rise of eCommerce in the later years. Of course, we also see a significant drop in gross capital formation around the time of the 2008 financial crisis, which also seems to have affected imports.</p>
<p>Last but not least, let us look at Germany. Looking at the visualization of the data, we see the most stable distribution of GDP components over the years between the three countries. Germany has been able to reliably maintain a trade surplus over most years. Especially since 2000, trade seems to have become more central to Germany´s GDP. Such an observation is not entirely surprising, giving that Germany has a strong footing in most large sectors (e.g. agriculture, pharma) and enjoys strong demand for its machinery and vehicles. Meanwhile, household expenditure contributes less to the GDP than observed in the other countries. This does not mean that Germans spend less, but that the GDP of Germany is just more evenly distributed between its components.</p>
</div>
